apiVersion: apps/v1
kind: Deployment
metadata:
  name: yc-scheduler
  namespace: yc-scheduler
  labels:
    app: yc-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yc-scheduler
  template:
    metadata:
      labels:
        app: yc-scheduler
    spec:
      containers:
        - name: yc-scheduler
          image: ghcr.io/sentoz/yc-sheduler:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: yc-scheduler-env
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: sa-key
              mountPath: /sa
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: yc-scheduler-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: sa-key
          secret:
            secretName: yc-sa-key
            items:
              - key: sa-key.json
                path: sa-key.json
