apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yc-scheduler

resources:
  - deployment.yaml

configMapGenerator:
  - name: yc-scheduler-config
    files:
      - config.yaml
  - name: yc-scheduler-env
    envs:
      - config.env
