name: Scan release

on:
  release:
    types: [published, created, released, edited]

permissions:
  contents: write

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Artifacts Scan
        uses: WoozyMasta/virustotal-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VT_API_KEY }}
          rate_limit: 4
          update_release: true
          file_globs: |
            yc-scheduler-darwin-*
            yc-scheduler-linux-*
            yc-scheduler-windows-*.exe
          excluded_extensions: ".json"
